version: '3.8'
services:
  scraper:
    build: .
    volumes:
      - ./docker-data:/app/data
    command:
      - --product_count=500
      - --page_size=96
      - --first_page_number=1
      - --requests_delay=1
